swagger: '2.0'
info:
  title: Statistics API
  version: "0.1"
  description: Statistics API Endpoints
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /invoice:
    post:
      tags: [ NewInvoice ]
      operationId: app.new_invoice
      summary: Update counters with new invoice
      parameters:
        - $ref: '#/parameters/invoice_body'
      responses:
        200:
          description: Return status
        400:
          description: Bad request

parameters:
  invoice_body:
    name: Invoice Body
    description: New invoice body
    in: body
    schema:
      required:
        - user_id
        - type_of_product
        - quantity
      properties:
        user_id:
          type: integer
        type_of_product:
          type: string
        quantity:
          type: integer
