swagger: '2.0'
info:
  title: Statistics API
  version: "0.1"
  description: Statistics API Endpoints
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /achievement/{achievement_id}:
    get:
      tags: [ Achievement ]
      operationId: app.get_achievement_by_id
      summary: Testing
      parameters:
        - $ref: '#/parameters/achievement_id'
      responses:
        200:
          description: Return status
parameters:
  achievement_id:
    name: achievement_id
    description: The id of the achievement
    in: path
    required: true
    type: integer
