"""Changed models2

Revision ID: 4e994769f518
Revises: 7897c151b0e4
Create Date: 2021-04-16 22:34:39.787320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e994769f518'
down_revision = '7897c151b0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achievements_helper')
    op.create_foreign_key(None, 'achievements', 'helper', ['achievement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_table('achievements_helper',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('achievement_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='achievements_helper_pkey')
    )
    op.drop_table('helper')
    # ### end Alembic commands ###
