"""Changed models

Revision ID: 7897c151b0e4
Revises: 
Create Date: 2021-04-16 22:20:10.284883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7897c151b0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements_helper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achievements__helper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements__helper',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('achievement_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='achievements__helper_pkey')
    )
    op.drop_table('achievements_helper')
    # ### end Alembic commands ###
